### ISSUE TITLE
Tone of book

### ISSUE THREAD

**Issue by eliasreid** [TianyiShi2001/cpp4r#1]
Hi there. Great idea for a resource, I am a C++ developer who has been learning Rust, so I think I can contribute to the docs.

I noticed in a few places, there are additional notes that sound a bit like bashing on C++ or the committee.

https://github.com/TianyiShi2001/cpp4r/blob/4e10d726274fed67c651dc45124a72cfa0ed0441/book/hello.Rmd#L462

https://github.com/TianyiShi2001/cpp4r/blob/4e10d726274fed67c651dc45124a72cfa0ed0441/book/hello.Rmd#L519

Is this the intended tone of the book? I certainly think it would make a better resource for people looking to learn C++ (by choice or not), without the added negativity.

**Comment by TianyiShi2001** [comment]
Thank you for your criticism and I agree with you. I sincerely apologize for those unproductive and opinionated words. I will rephrase them A.S.A.P. Different programming languages work in different ways and it's better to let the user/reader judge which is better, not the designers or authors of a tutorial of an language.

**Comment by TianyiShi2001** [comment]
Addressed in https://github.com/TianyiShi2001/cpp4r/commit/d1eac498a2cdac6e77ddb69134702d653acbccbc
